#!/usr/bin/env python3
"""THE ONE HARD PARENT -- exhaustive n=31 classification by automorphism collapse.

WHY THIS FILE EXISTS
--------------------
`classify.py` finishes every marked parent in the n <= 38 ladder except one:
weight-32 class 0 marked odd, which is the set of all 31 nonzero points of
F_2^5.  That parent is maximally symmetric -- *every* invertible 5x5 matrix over
F_2 permutes the nonzero points, so its automorphism group is the whole of
GL(5,2), of order 9,999,360 -- and its quotient V = R(C)/C has dimension 11.
Plain frame enumeration over 2^11 - 1 points therefore revisits the same gate
millions of times, and a naive run either takes hours or trips the node budget.

The fix is to use the symmetry instead of fighting it.  A qubit relabelling by
M in GL(5,2) is a physical relabelling of the factory: it permutes the 31
columns and preserves the check code, so it maps factories to factories and
leaves the logical gate unchanged (up to nothing at all -- the gate is
invariant, which is checked below rather than assumed).  Hence:

    every compatible frame is GL(5,2)-equivalent to one whose FIRST output is
    one of the few orbit representatives of the induced action on V,

and fixing the first output to an orbit representative loses no gate class
while cutting the search by orders of magnitude.

WHAT IT DOES
------------
`induced_V_action` transports GL(5,2), generated by elementary transvections,
through the quotient construction to get its induced linear action on V.
`main()` then demonstrates the collapse is sound:

  (a) it counts the orbits of the 2047 nonzero quotient points,
  (b) it checks that the degree-1 output parity is constant on each orbit and
      spot-checks that whole logical gates are orbit-invariant,
  (c) it reports the level-1 collapse ratio actually achieved.

`complete_hard_parent(kmax)` then runs the reduced enumeration to completion and
returns one record per S_k gate class, each with explicit verified columns.  At
kmax=5 this is where the unique [[31,5,3]] class -- the widest factory anywhere
in the n <= 38 window -- comes from.

Run:  python hard_parent_n31.py [--kmax 5] [--output results/hard_parent_n31.json]
"""

import itertools
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parents[1]))

from classify import (marked_all, quotient_reps, rref_basis,        # noqa: E402
                      reduce_mod, compat_adjacency, frame_wants)
from dedup import sk_canonical, sk_canonical_with_perm, sk_name     # noqa: E402
from marking import row_space_rows                                  # noqa: E402


def get_parent():
    """The n=31 class-0 marked parent: weight-32 class 0 is the constant-1
    polynomial on F_2^5 (full space), so every odd marking gives the same
    31 nonzero points; the first yielded instance suffices."""
    for ci, r, cs in marked_all(31):
        if ci == 0:
            return r, cs
    raise RuntimeError


def matvec(M, p, r):
    """Apply 5x5 matrix M (list of row-ints over 5 bits) to point p."""
    out = 0
    for i in range(r):
        if (M[i] & p).bit_count() & 1:
            out |= 1 << i
    return out


def gl_transvections(r):
    """Elementary transvections T_{ij} (add basis i to basis j); together they
    generate GL(r,2)."""
    gens = []
    for i in range(r):
        for j in range(r):
            if i == j:
                continue
            M = [1 << k for k in range(r)]     # identity rows
            M[j] ^= (1 << i)                   # row j += row i
            gens.append(M)
    return gens


def induced_V_action(cs, r):
    """Return (Vreps, coord, dimV, adj-ready data, list of 11x11 gens on V)."""
    Vreps, hlist, Qbasis, n = quotient_reps(cs, r)
    dimV = len(Qbasis)
    Crref = rref_basis(hlist)
    coord = {Vreps[x]: x for x in range(1 << dimV)}
    checks = tuple(cs)
    idx = {p: i for i, p in enumerate(checks)}          # point -> column index

    def perm_of(M):
        # column permutation induced by point map p -> M p
        perm = [0] * n
        for i, p in enumerate(checks):
            perm[i] = idx[matvec(M, p, r)]
        return perm

    def apply_perm_vec(perm, a):
        out = 0
        for i in range(n):
            if (a >> i) & 1:
                out |= 1 << perm[i]
        return out

    Vgens = []
    for M in gl_transvections(r):
        perm = perm_of(M)
        # image of each V-basis vector, as a V-coordinate
        cols = []
        for b in range(dimV):
            img = apply_perm_vec(perm, Qbasis[b])
            img = reduce_mod(img, Crref)
            cols.append(coord[img])            # coordinate integer of the image
        Vgens.append(cols)                     # cols[b] = image coord of basis b
    return Vreps, coord, dimV, hlist, Qbasis, Vgens


def act_on_coord(Vgen, x, dimV):
    """Apply a V-generator (given as images of basis coords) to coordinate x."""
    y = 0
    for b in range(dimV):
        if (x >> b) & 1:
            y ^= Vgen[b]
    return y


def orbits(points, gens, dimV):
    """Orbit partition of coordinate `points` under the group GENERATED by
    `gens` (BFS closure), as (reps, rep_of)."""
    seen = {}
    reps = []
    for p in points:
        if p in seen:
            continue
        rep = p
        reps.append(rep)
        stack = [p]
        seen[p] = rep
        while stack:
            q = stack.pop()
            for g in gens:
                qq = act_on_coord(g, q, dimV)
                if qq not in seen:
                    seen[qq] = rep
                    stack.append(qq)
    return reps, seen


def main():
    """Soundness demonstration for the collapse: orbit counts, the asserted
    orbit-invariance of the single parity, a gate-invariance spot check, and
    the level-1 collapse ratio.  The actual classification is
    complete_hard_parent()."""
    r, cs = get_parent()
    Vreps, coord, dimV, hlist, Qbasis, Vgens = induced_V_action(cs, r)
    print(f'parent: {len(cs)} points in F_2^{r}, dimV={dimV}, |V\\0|={(1<<dimV)-1}')
    print(f'|GL({r},2)| = {gl_order(r):,}  (the automorphism group order)')

    pts = list(range(1, 1 << dimV))
    reps, seen = orbits(pts, Vgens, dimV)
    print(f'\n(a) orbits of the {len(pts)} nonzero quotient points under the '
          f'induced action: {len(reps)}')
    # invariant check: single parity constant on each orbit
    from collections import defaultdict
    byrep = defaultdict(list)
    for p in pts:
        byrep[seen[p]].append(p)
    for rep in reps:
        singles = {Vreps[p].bit_count() & 1 for p in byrep[rep]}
        if len(singles) != 1:
            # The premise of the whole collapse: if the gate were not invariant
            # on an orbit, fixing one representative per orbit would lose
            # classes.  Not an assert -- `python -O` would skip the check that
            # makes this run a classification rather than a sample.
            raise RuntimeError(
                'single parity is not constant on an orbit, so the GL(5,2) '
                'collapse is unsound for this parent')
    print('    single parity is constant on every orbit (as required).')

    # (b) gate invariance on random-ish independent pairs
    comp = compat_adjacency(Vreps, hlist, Qbasis)
    checked = 0
    for x in reps[:6]:
        for y in pts:
            if x == y or not comp[x][y]:
                continue
            g = Vgens[0]
            gx, gy = act_on_coord(g, x, dimV), act_on_coord(g, y, dimV)
            w1 = sk_canonical(2, frame_wants(Vreps, (x, y)))
            w2 = sk_canonical(2, frame_wants(Vreps, (gx, gy)))
            if w1 != w2:
                raise RuntimeError(
                    f'gate {sk_name(w1)} maps to {sk_name(w2)} under an '
                    f'automorphism, so the collapse is unsound')
            checked += 1
            if checked > 2000:
                break
        if checked > 2000:
            break
    print(f'(b) gate invariant under the action on {checked} compatible pairs '
          '(spot check): PASS')

    # (c) collapse of compatible ORDERED pairs -> orbits (illustrative count)
    #     count compatible ordered pairs, and orbit-reps with first output fixed
    #     to an orbit rep (the practical canonical-augmentation cut).
    # (ncompat is illustrative only and not used below)
    ncompat = int(comp.sum()) - (1 << dimV)     # minus diagonal falses already 0
    # comp includes 0-row/col; restrict to nonzero
    npairs = sum(1 for x in pts for y in pts if x != y and comp[x][y])
    # with first output fixed to orbit reps:
    reduced = sum(1 for x in reps for y in pts if x != y and comp[x][y])
    print(f'\n(c) compatible ordered pairs (nonzero): {npairs:,}')
    print(f'    with first output restricted to {len(reps)} orbit reps: '
          f'{reduced:,}  (~{npairs/max(reduced,1):.0f}x cut at level 1 alone)')


#: Width the n <= 38 catalogue needs from this parent: the unique [[31,5,3]]
#: class, the widest factory anywhere in the window, appears at k=5.
CATALOGUE_KMAX = 5


def gl_order(r):
    o = 1
    for i in range(r):
        o *= (1 << r) - (1 << i)
    return o


def complete_hard_parent(kmax=4):
    """Exhaustive gate classification for the n=31 F_2^5 parent, using the
    automorphism collapse: fix the first output to one of the 5 orbit reps
    (every frame is Aut-equivalent to one such, and the gate is Aut-invariant),
    then enumerate the rest freely.  Complete, and fast."""
    from classify import build_columns, indep
    from factorylib.verification import verify
    import numpy as np

    r, cs = get_parent()
    Vreps, coord, dimV, hlist, Qbasis, Vgens = induced_V_action(cs, r)
    pts = list(range(1, 1 << dimV))
    reps, _ = orbits(pts, Vgens, dimV)
    comp = compat_adjacency(Vreps, hlist, Qbasis)
    packed = np.packbits(comp, axis=1, bitorder='little')
    adj = [0] * (1 << dimV)
    for x in pts:
        m = int.from_bytes(packed[x].tobytes(), 'little')
        adj[x] = m & ~1 & ~(1 << x)

    from dedup import canonical_gate
    gates = {}                      # perm-canonical -> record dict

    def record(frame):
        wants = frame_wants(Vreps, frame)
        if not wants:
            return
        k = len(frame)
        cov = set()
        for Q in wants:
            cov |= set(Q)
        if len(cov) != k:
            return
        pc, perm = sk_canonical_with_perm(k, wants)
        if pc in gates:
            return
        # store the witness in the canonical frame (output i -> perm[i]) so the
        # columns deposit exactly the `gate` string this row is filed under
        a_vectors = [0] * k
        for i, x in enumerate(frame):
            a_vectors[perm[i]] = Vreps[x]
        canonical_wants = {frozenset(perm[i] for i in Q) for Q in wants}
        cols = build_columns(cs, r, k, a_vectors)
        # parent points are distinct and nonzero, so columns cannot repeat
        if len(set(cols)) != len(cols):
            raise RuntimeError('repeated column from a marked parent, whose '
                               'points are distinct and nonzero')
        ok, dist = verify(k, k + r, cols, canonical_wants, dmax=4)
        if not ok:
            raise RuntimeError(
                f'the independent verifier rejects the parity tensor of the '
                f'{sk_name(pc)} witness at k={k}')
        gates[pc] = {
            'n': 31, 'k': k, 'r': r, 'rows': k + r, 'distance': dist,
            'gate': sk_name(pc), 'gate_gl_canonical': canonical_gate(k, wants),
            'columns': [sorted(c) for c in cols], 'class_index': 0,
            'certified': 'complete via GL(5,2) automorphism reduction',
        }

    def grow(frame, cand_mask, brref):
        if len(frame) >= 1:
            record(frame)
        if len(frame) == kmax:
            return
        m = cand_mask
        while m:
            y = (m & -m).bit_length() - 1
            m &= m - 1
            if len(frame) >= 2 and y <= frame[-1]:
                continue          # order outputs 2..k among themselves
            res = indep(brref, y)
            if res == 0:
                continue
            nb = dict(brref); nb[res.bit_length() - 1] = res
            grow(frame + (y,), cand_mask & adj[y], nb)

    for r0 in reps:
        grow((r0,), adj[r0], {r0.bit_length() - 1: r0})

    recs = list(gates.values())
    from collections import Counter
    bykd = Counter(rr['k'] for rr in recs)
    print(f'\n=== exhaustive n=31 gate classification via GL(5,2) collapse '
          f'(kmax={kmax}) ===')
    for k in sorted(bykd):
        print(f'  k={k}: {bykd[k]} gate(s): ' + ', '.join(
            f'{rr["gate"]}(d{rr["distance"]})' for rr in
            sorted(recs, key=lambda z: z['gate']) if rr['k'] == k))
    return recs


def cli(argv=None):
    """CLI: demonstrate the collapse, run it to completion, write the records."""
    import argparse
    import json
    from pathlib import Path

    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--kmax', type=int, default=CATALOGUE_KMAX,
                    help=f'largest output width to enumerate (default '
                         f'{CATALOGUE_KMAX}, which is where the unique '
                         f'[[31,5,3]] class appears; a narrower run writes '
                         f'complete=false and build_catalog.py refuses it)')
    ap.add_argument('--output', default=None,
                    help='destination JSON (default results/hard_parent_n31.json)')
    ap.add_argument('--quiet', action='store_true',
                    help='skip the soundness demonstration in main()')
    args = ap.parse_args(argv)

    if not args.quiet:
        main()
    recs = complete_hard_parent(kmax=args.kmax)
    recs.sort(key=lambda r: (r['k'], r['gate']))

    here = Path(__file__).resolve().parent
    out = Path(args.output) if args.output else here / 'results' / 'hard_parent_n31.json'
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps({
        'scope': 'n=31, weight-32 class 0 marked odd (all 31 nonzero points of '
                 'F_2^5): complete gate classification by GL(5,2) automorphism '
                 'collapse',
        'method': 'first output restricted to one representative per orbit of '
                  'the induced GL(5,2) action on V = R(C)/C; the logical gate '
                  'is orbit-invariant, so no class is lost',
        'automorphism_group': f'GL(5,2), order {gl_order(5)}',
        'dedup_signature': '(n, k, S_k-canonical gate); see dedup.py',
        'kmax': args.kmax,
        # `complete` means "this file may be used as a classification input",
        # and the enumeration finishing is only half of that: a narrower --kmax
        # finishes just as cleanly while omitting the widest class in the whole
        # window.  build_catalog.py reads both this flag and `kmax`.
        'complete': args.kmax >= CATALOGUE_KMAX,
        'incomplete_reasons': [] if args.kmax >= CATALOGUE_KMAX else [
            f'--kmax {args.kmax} < {CATALOGUE_KMAX}: complete for widths up to '
            f'{args.kmax} only, so the unique [[31,5,3]] class is absent'],
        'distinct_factories': len(recs),
        'factories': recs,
    }, indent=2) + '\n')
    print(f'\n{len(recs)} gate classes -> {out}')
    if args.kmax < CATALOGUE_KMAX:
        print(f'NOTE: complete=false -- --kmax {args.kmax} is below the '
              f'{CATALOGUE_KMAX} the catalogue needs, so this file is search '
              f'data and build_catalog.py will refuse it.')
        return 1
    return 0


if __name__ == '__main__':
    raise SystemExit(cli())
